import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
import {validateProject,clone,escapeHTML as esc,compileWorld,meshWorld,rotatedSize,paintCells,cellAt,moveVisitor,fitsVisitor,navigationReport} from './project.mjs';
import {exportGLB,exportVOX,importVOX,addImportedAsset} from './formats.mjs';
import {zipFiles} from './archive.mjs';
import {EditSession} from './edit-session.mjs';

const originalHTML='<!doctype html>'+document.documentElement.outerHTML;
const $=id=>document.getElementById(id),data=JSON.parse($('world-data').textContent),readonly=data.mode==='walk';
let project=validateProject(data.project),selected=project.objects.find(o=>!o.locked&&!o.hidden)?.id??project.objects[0].id,material=project.materials[0].id;
let world,meshes=[],tool='select',walking=false,visitor,pitch=0,connected=false,saving=false,sourcePending=null,pollEpoch=0,cycle=0;
const session=new EditSession(project),{past,future}=session,keys=new Set(),viewport=$('viewport');
const report=message=>{$('status').textContent=message;};
function failure(error){renderUI();report(error.message);const dialog=document.querySelector('dialog[open]');if(dialog){let notice=dialog.querySelector('[data-error]');if(!notice){notice=document.createElement('p');notice.dataset.error='';notice.setAttribute('role','alert');notice.style.color='#a24b2f';dialog.append(notice);}notice.textContent=error.message;}}
const guard=fn=>(...args)=>{try{const result=fn(...args);if(result?.catch)result.catch(failure);}catch(error){failure(error);}};
const download=(name,body,type='application/octet-stream')=>{const url=URL.createObjectURL(body instanceof Blob?body:new Blob([body],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);};
const stamp=()=>new Date().toISOString().slice(0,19).replace(/[:T]/g,'-');
const state=()=>{$('save-state').textContent=session.dirty?'Unsaved changes':connected?'Saved in workspace':'Editable offline project';$('save-source').hidden=!connected||readonly;$('save-source').disabled=!session.dirty||saving||Boolean(sourcePending);$('undo').disabled=!past.length;$('redo').disabled=!future.length;};
function saveDraft(){try{session.persistDraft(localStorage);}catch{report('Browser draft storage is unavailable. Download your project to keep these changes.');}}
function mutate(fn,message='World updated'){
  if(readonly)return;const next=clone(project);fn(next);const valid=validateProject(next);
  // Mesh before committing, so an over-budget scene cannot replace a working draft.
  const compiled=compileWorld(valid),geometry=meshWorld(valid,compiled);
  session.edit(valid);project=session.project;world=compiled;renderWorld(geometry);renderUI();report(message);saveDraft();
}
function history(from,to){if(!session.restoreHistory(from,to))return;project=session.project;rebuild();report('Edit history restored');saveDraft();}
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(43,1,.1,2000),renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;viewport.append(renderer.domElement);
const ambient=new THREE.HemisphereLight('#f1f1d9','#66716e',2.2),sun=new THREE.DirectionalLight('#ffedd1',3.1);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.normalBias=.05;sun.shadow.bias=-.0001;scene.add(ambient,sun,sun.target);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.dampingFactor=.09;orbit.maxPolarAngle=Math.PI*.49;orbit.minDistance=3;orbit.maxDistance=300;
const anchor=new THREE.Object3D();scene.add(anchor);const transform=new TransformControls(camera,renderer.domElement);transform.setTranslationSnap(1);transform.setSize(.65);scene.add(transform.getHelper());
const selectionBox=new THREE.Box3Helper(new THREE.Box3(),new THREE.Color('#da9a52'));selectionBox.material.depthTest=false;selectionBox.renderOrder=5;scene.add(selectionBox);
const hitBox=new THREE.Mesh(new THREE.BoxGeometry(1.015,1.015,1.015),new THREE.MeshBasicMaterial({color:'#fff2c7',wireframe:true,depthTest:false}));hitBox.visible=false;hitBox.renderOrder=6;scene.add(hitBox);
let grid,ground,dragOrigin=null,transformDragging=false;const glowLights=[];
function selectedObject(){return project.objects.find(o=>o.id===selected);}
function syncSelection(){const o=selectedObject();selectionBox.visible=Boolean(o&&!o.hidden&&!walking);transform.detach();if(!o||o.hidden)return;const size=rotatedSize(o);selectionBox.box.set(new THREE.Vector3(...o.origin),new THREE.Vector3(...o.origin.map((n,i)=>n+size[i])));anchor.position.set(...o.origin);if(tool==='select'&&!o.locked&&!walking&&!readonly)transform.attach(anchor);}
transform.addEventListener('dragging-changed',event=>{
  transformDragging=event.value;orbit.enabled=!event.value&&!walking;
  if(event.value)dragOrigin=[...selectedObject().origin];
  else if(dragOrigin){const next=anchor.position.toArray().map(Math.round);dragOrigin=null;try{mutate(p=>{p.objects.find(o=>o.id===selected).origin=next;},'Object moved');}catch(error){rebuild();report(error.message);}syncSelection();}
});
transform.addEventListener('objectChange',()=>{
  if(!dragOrigin)return;const o=selectedObject(),size=rotatedSize(o);anchor.position.fromArray(anchor.position.toArray().map((n,i)=>Math.max(0,Math.min(project.size[i]-size[i],Math.round(n)))));
  const delta=anchor.position.toArray().map((n,i)=>n-dragOrigin[i]);for(const mesh of meshes)if(mesh.userData.id===selected)mesh.position.set(...delta);
  selectionBox.box.set(anchor.position.clone(),anchor.position.clone().add(new THREE.Vector3(...size)));
});
function dispose(mesh){mesh.geometry?.dispose();if(Array.isArray(mesh.material))mesh.material.forEach(m=>m.dispose());else mesh.material?.dispose();scene.remove(mesh);}
function lighting(value=project.light){
  const t=value*2*Math.PI,day=Math.max(.05,Math.sin(t)),span=Math.max(...project.size);scene.background=new THREE.Color().lerpColors(new THREE.Color('#182732'),new THREE.Color('#dbe1d2'),day);scene.fog=new THREE.Fog(scene.background,span*2,span*6);
  sun.position.set(project.size[0]/2+Math.cos(t)*span,Math.max(10,Math.sin(t)*span),project.size[2]*1.5);sun.target.position.set(project.size[0]/2,0,project.size[2]/2);sun.intensity=.25+day*2.7;ambient.intensity=.55+day*1.5;
  sun.shadow.camera.left=-span;sun.shadow.camera.right=span;sun.shadow.camera.top=span;sun.shadow.camera.bottom=-span;sun.shadow.camera.far=span*5;sun.shadow.camera.updateProjectionMatrix();
}
function renderWorld(geometry){
  for(const m of meshes)dispose(m);meshes=[];
  for(const light of glowLights)scene.remove(light);glowLights.length=0;
  for(const g of geometry){const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(g.positions,3));geo.setAttribute('normal',new THREE.Float32BufferAttribute(g.normals,3));geo.setIndex(g.indices);geo.computeBoundingSphere();const m=project.materials.find(m=>m.id===g.material),mat=new THREE.MeshStandardMaterial({color:m.color,roughness:.86,metalness:0,transparent:m.opacity<1,opacity:m.opacity,depthWrite:m.opacity===1,emissive:m.color,emissiveIntensity:m.emission*.55});const mesh=new THREE.Mesh(geo,mat);mesh.castShadow=m.opacity===1;mesh.receiveShadow=true;mesh.userData={id:project.objects[g.object].id,material:g.material};meshes.push(mesh);scene.add(mesh);}
  for(const mesh of meshes){const material=project.materials.find(m=>m.id===mesh.userData.material);if(material.emission>0&&glowLights.length<12){mesh.geometry.computeBoundingBox();const light=new THREE.PointLight(material.color,material.emission*45,18,2);mesh.geometry.boundingBox.getCenter(light.position);glowLights.push(light);scene.add(light);}}
  if(grid)dispose(grid);const span=Math.max(project.size[0],project.size[2]);grid=new THREE.GridHelper(span,Math.ceil(span/4),'#879685','#b3bcab');grid.position.set(project.size[0]/2,-.03,project.size[2]/2);grid.material.transparent=true;grid.material.opacity=.4;scene.add(grid);
  if(ground)dispose(ground);ground=new THREE.Mesh(new THREE.PlaneGeometry(span*12,span*12),new THREE.MeshStandardMaterial({color:'#c4ccbb',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.set(project.size[0]/2,-.07,project.size[2]/2);ground.receiveShadow=true;scene.add(ground);
  lighting();syncSelection();$('scene-measures').textContent=`${world.count.toLocaleString()} voxels · ${project.size.map(n=>(n*project.unit).toFixed(1)).join(' × ')} m`;
}
function rebuild(){world=compileWorld(project);renderWorld(meshWorld(project,world));renderUI();if(walking&&visitor&&!fitsVisitor(world,visitor.position)){setWalking(false);report('The world changed around the visitor. Review it before walking again.');}}
function frame(bounds){const box=bounds??new THREE.Box3(new THREE.Vector3(0,0,0),new THREE.Vector3(project.size[0],Math.max(...project.objects.filter(o=>!o.hidden).map(o=>o.origin[1]+rotatedSize(o)[1]),2),project.size[2]));const center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),distance=Math.max(...size.toArray())*1.35;if(!bounds)center.y*=.55;orbit.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(distance*.8,distance*.65,distance*.95));camera.lookAt(center);orbit.update();}
function setSelected(id){selected=id;syncSelection();renderUI();}
function setTool(value){tool=value;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));orbit.mouseButtons.LEFT=tool==='select'?THREE.MOUSE.ROTATE:-1;orbit.mouseButtons.RIGHT=THREE.MOUSE.ROTATE;syncSelection();hitBox.visible=false;$('interaction-hint').textContent=tool==='select'?'Drag to orbit · click to select · arrows move objects':'Click to sculpt selected object · right-drag to orbit';}
function renderUI(){
  $('world-title').textContent=project.title;document.title=project.title+' — Tidelands';$('brief-text').textContent=project.brief;$('object-count').textContent=project.objects.length+' objects';$('light').value=project.light;
  const query=$('object-search').value.toLowerCase();$('object-list').innerHTML=project.objects.filter(o=>o.name.toLowerCase().includes(query)).map(o=>`<div class="object-row ${o.id===selected?'selected':''} ${o.hidden?'hidden-object':''}"><button data-object="${o.id}" title="${esc(o.name)}"><span class="dot"></span>${esc(o.name)}</button><button class="toggle" data-visible="${o.id}" title="${o.hidden?'Show':'Hide'} ${esc(o.name)}">${o.hidden?'○':'●'}</button><button class="toggle" data-lock="${o.id}" title="${o.locked?'Unlock':'Lock'} ${esc(o.name)}">${o.locked?'▣':'□'}</button></div>`).join('');
  const o=selectedObject();$('object-editor').innerHTML=o?`<label>Name<input id="object-name" value="${esc(o.name)}" ${o.locked?'disabled':''}></label><label>Position · voxels<div class="xyz">${['X','Y','Z'].map((axis,i)=>`<label>${axis}<input data-position="${i}" type="number" step="1" min="0" value="${o.origin[i]}" ${o.locked?'disabled':''}></label>`).join('')}</div></label><div class="fine">${rotatedSize(o).map(n=>(n*project.unit).toFixed(1)).join(' × ')} m · ${o.locked?'locked':'editable'}</div><div class="actions"><button id="rotate-object" ${o.locked?'disabled':''}>Rotate 90°</button><button id="duplicate-object">Duplicate</button><button id="delete-object" ${o.locked||project.objects.length===1?'disabled':''}>Delete</button></div><div class="actions"><button id="asset-glb">Asset .glb ↗</button><button id="asset-vox">Asset .vox ↗</button></div>`:'Choose an object to edit its geometry.';
  $('palette').innerHTML=project.materials.map(m=>`<button data-material="${m.id}" title="${esc(m.name)}" aria-label="${esc(m.name)}" style="background:${m.color}" class="${m.id===material?'active':''}"></button>`).join('');
  const m=project.materials.find(m=>m.id===material)??project.materials[0];material=m.id;$('material-editor').innerHTML=`<div class="color-row"><input id="material-color" aria-label="Material color" type="color" value="${m.color}"><input id="material-name" aria-label="Material name" value="${esc(m.name)}"></div><label class="check"><input id="material-solid" type="checkbox" ${m.solid?'checked':''}> Blocks walking</label><label>Opacity<input id="material-opacity" type="range" min=".05" max="1" step=".01" value="${m.opacity}"></label><label>Glow<input id="material-glow" type="range" min="0" max="1" step=".05" value="${m.emission}"></label>`;
  $('tour-stops').innerHTML=project.stops.map(s=>`<button data-stop="${s.id}" title="${esc(s.description)}">${esc(s.name)} ↗</button>`).join('');state();
}
$('object-list').onclick=guard(event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.object)setSelected(b.dataset.object);if(b.dataset.visible)mutate(p=>{const o=p.objects.find(o=>o.id===b.dataset.visible);o.hidden=!o.hidden;},'Object visibility changed');if(b.dataset.lock)mutate(p=>{const o=p.objects.find(o=>o.id===b.dataset.lock);o.locked=!o.locked;},'Object lock changed');});
$('object-search').oninput=renderUI;
$('object-editor').onchange=guard(event=>{const id=event.target.id;if(id==='object-name')mutate(p=>{p.objects.find(o=>o.id===selected).name=event.target.value;});if(event.target.dataset.position)mutate(p=>{p.objects.find(o=>o.id===selected).origin[Number(event.target.dataset.position)]=Number(event.target.value);},'Object moved');});
$('object-editor').onclick=guard(event=>{const id=event.target.closest('button')?.id,o=selectedObject();if(!o)return;
  if(id==='rotate-object')mutate(p=>{p.objects.find(o=>o.id===selected).rotation=(o.rotation+1)%4;},'Object rotated');
  if(id==='duplicate-object'){const newid=unique(o.id);mutate(p=>{const copy=clone(o);copy.id=newid;copy.name+=' copy';copy.locked=false;copy.origin=copy.origin.map((n,i)=>i===0?Math.min(project.size[0]-rotatedSize(copy)[0],n+2):n);p.objects.push(copy);},'Object duplicated');setSelected(newid);}
  if(id==='delete-object'){mutate(p=>{p.objects=p.objects.filter(o=>o.id!==selected);},'Object removed');setSelected(project.objects[0].id);}
  if(id==='asset-glb')download(o.id+'.glb',exportGLB(project,{objectId:o.id}),'model/gltf-binary');if(id==='asset-vox')download(o.id+'.vox',exportVOX(project,{objectId:o.id}));
});
function unique(prefix){let id=prefix,n=2;while(project.objects.some(o=>o.id===id))id=prefix.slice(0,56)+'-'+n++;return id;}
$('new-object').onclick=guard(()=>{const id=unique('object');mutate(p=>p.objects.push({id,name:'New voxel object',origin:[Math.floor(p.size[0]/2),Math.min(p.size[1]-1,Math.floor(project.spawn.position[1])),Math.floor(p.size[2]/2)],size:[1,1,1],boxes:[[0,0,0,1,1,1,material]],edits:[],rotation:0,hidden:false,locked:false}),'New object added');setSelected(id);setTool('add');});
$('palette').onclick=event=>{const b=event.target.closest('[data-material]');if(b){material=Number(b.dataset.material);renderUI();}};
$('material-editor').onchange=guard(event=>{const map={'material-name':['name',event.target.value],'material-color':['color',event.target.value],'material-solid':['solid',event.target.checked],'material-opacity':['opacity',Number(event.target.value)],'material-glow':['emission',Number(event.target.value)]};const entry=map[event.target.id];if(entry)mutate(p=>{p.materials.find(m=>m.id===material)[entry[0]]=entry[1];},'Material updated across the world');});
$('new-material').onclick=guard(()=>{const id=Array.from({length:255},(_,i)=>i+1).find(id=>!project.materials.some(m=>m.id===id));if(!id)throw new Error('The palette already has 255 materials.');mutate(p=>p.materials.push({id,name:'New material',color:'#c58b65',solid:true,opacity:1,emission:0}));material=id;renderUI();});
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));$('undo').onclick=()=>history(past,future);$('redo').onclick=()=>history(future,past);
$('light').oninput=event=>lighting(Number(event.target.value));$('light').onchange=guard(event=>mutate(p=>{p.light=Number(event.target.value);},'Light saved'));$('cycle-light').onchange=()=>{cycle=project.light;};
$('frame-world').onclick=()=>{if(walking)setWalking(false);frame();};$('focus-object').onclick=()=>{if(selectedObject())frame(selectionBox.box);};
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let down=null,lookDrag=null;
function hit(event){const rect=renderer.domElement.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-((event.clientY-rect.top)/rect.height)*2+1);raycaster.setFromCamera(pointer,camera);return raycaster.intersectObjects(meshes,false)[0];}
function voxelPosition(h,add){const point=h.point.clone().addScaledVector(h.face.normal,add?.001:-.001);return point.toArray().map(Math.floor);}
renderer.domElement.addEventListener('pointerdown',event=>{viewport.focus();down={x:event.clientX,y:event.clientY,button:event.button};if(walking&&!document.pointerLockElement){lookDrag={x:event.clientX,y:event.clientY};renderer.domElement.setPointerCapture(event.pointerId);}});
renderer.domElement.addEventListener('pointermove',event=>{
  if(walking){if(document.pointerLockElement||lookDrag){const dx=document.pointerLockElement?event.movementX:event.clientX-lookDrag.x,dy=document.pointerLockElement?event.movementY:event.clientY-lookDrag.y;visitor.yaw-=dx*.003;pitch=Math.max(-1.45,Math.min(1.45,pitch-dy*.003));if(lookDrag)lookDrag={x:event.clientX,y:event.clientY};}return;}
  if(tool==='select'||transformDragging){hitBox.visible=false;return;}const h=hit(event);hitBox.visible=Boolean(h);if(h)hitBox.position.set(...voxelPosition(h,tool==='add').map(n=>n+.5));
});
renderer.domElement.addEventListener('pointerup',guard(event=>{lookDrag=null;if(walking||transformDragging||!down||down.button!==0||Math.hypot(event.clientX-down.x,event.clientY-down.y)>4)return;const h=hit(event);if(!h)return;if(tool==='select'){setSelected(h.object.userData.id);return;}const at=voxelPosition(h,tool==='add');if(at.some((n,i)=>n<0||n>=project.size[i]))throw new Error('The brush is outside the world. Enlarge the project to build here.');
  if(tool!=='add'&&h.object.userData.id!==selected)throw new Error('Select that object before changing its voxels.');
  mutate(p=>paintCells(p,selected,at,tool==='erase'?0:material,Number($('brush-radius').value),{existingOnly:tool==='paint'}),tool==='erase'?'Voxels removed':tool==='paint'?'Voxels painted':'Voxels added');
}));
renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());
function resetVisitor(position=project.spawn.position){if(!fitsVisitor(world,position))throw new Error('This destination has insufficient room for a 1.7 m visitor. Check the walking routes.');visitor={position:[...position],yaw:project.spawn.yaw,velocity:0,grounded:true};pitch=0;}
function setWalking(value){if(value){resetVisitor();}else{document.exitPointerLock?.();}walking=value;document.body.classList.toggle('walking',walking);$('interaction-hint').textContent=value?'WASD · drag to look · Space to jump':'Drag to orbit · click to select';$('walk-overlay').hidden=!value;$('crosshair').hidden=!value;$('touch-walk').hidden=!value||!matchMedia('(pointer:coarse)').matches;$('edit-tools').hidden=value||readonly;$('walk-mode').classList.toggle('active',value);$('edit-mode').classList.toggle('active',!value);orbit.enabled=!value;keys.clear();syncSelection();if(!value)frame();resize();}
$('walk-mode').onclick=guard(()=>setWalking(true));$('edit-mode').onclick=()=>setWalking(false);$('enter-walk').onclick=guard(async()=>{try{await renderer.domElement.requestPointerLock();}catch{report('Drag the view to look around; keyboard and touch walking remain available.');}viewport.focus();});
$('tour-stops').onclick=guard(event=>{const stop=project.stops.find(s=>s.id===event.target.dataset.stop);if(stop){resetVisitor(stop.position);report(stop.name+' · '+stop.description);}});
document.addEventListener('pointerlockchange',()=>{$('enter-walk').hidden=Boolean(document.pointerLockElement);});
window.addEventListener('keydown',guard(event=>{if(event.target.matches('input,textarea,select'))return;if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='z'){event.preventDefault();history(event.shiftKey?future:past,event.shiftKey?past:future);return;}if(walking&&['KeyW','KeyA','KeyS','KeyD','Space','ShiftLeft','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(event.code)){event.preventDefault();keys.add(event.code);}else if(!walking&&!readonly&&event.code.startsWith('Arrow')&&selectedObject()&&!selectedObject().locked){event.preventDefault();const axis=event.code==='ArrowLeft'||event.code==='ArrowRight'?0:2,delta=event.code==='ArrowLeft'||event.code==='ArrowUp'?-1:1;mutate(p=>{p.objects.find(o=>o.id===selected).origin[axis]+=delta;},'Object nudged');}}));
window.addEventListener('keyup',event=>keys.delete(event.code));window.addEventListener('blur',()=>keys.clear());
const touchKeys={forward:'KeyW',back:'KeyS',left:'KeyA',right:'KeyD',jump:'Space'};document.querySelectorAll('[data-move]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(touchKeys[b.dataset.move]);};b.onpointerup=b.onpointercancel=()=>keys.delete(touchKeys[b.dataset.move]);});
let last=performance.now(),accumulator=0;
function animate(now){requestAnimationFrame(animate);const dt=Math.min(.06,(now-last)/1000);last=now;if(walking&&visitor){accumulator+=dt;while(accumulator>=1/120){visitor=moveVisitor(world,visitor,{forward:(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0),right:(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),sprint:keys.has('ShiftLeft'),jump:keys.has('Space')},1/120);keys.delete('Space');accumulator-=1/120;}camera.position.set(visitor.position[0],visitor.position[1]+1.58/project.unit,visitor.position[2]);camera.lookAt(camera.position.clone().add(new THREE.Vector3(Math.sin(visitor.yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(visitor.yaw)*Math.cos(pitch))));}else orbit.update();if($('cycle-light').checked){cycle=(cycle+dt/120)%1;lighting(cycle);}renderer.render(scene,camera);}
function resize(){const {width,height}=viewport.getBoundingClientRect();if(!width||!height)return;camera.aspect=width/height;camera.updateProjectionMatrix();renderer.setSize(width,height,false);}new ResizeObserver(resize).observe(viewport);
$('edit-project').onclick=()=>{$('project-title').value=project.title;$('project-brief').value=project.brief;$('project-notes').value=project.notes;$('project-unit').value=project.unit;['x','y','z'].forEach((c,i)=>$('size-'+c).value=project.size[i]);$('project-dialog').showModal();};
$('apply-project').onclick=guard(()=>{mutate(p=>{p.title=$('project-title').value;p.brief=$('project-brief').value;p.notes=$('project-notes').value;p.unit=Number($('project-unit').value);p.size=['x','y','z'].map(c=>Number($('size-'+c).value));},'Project settings saved');$('project-dialog').close();});
function portable(mode='edit'){const payload=JSON.stringify({project,mode}).replace(/</g,'\\u003c');return originalHTML.replace(/(<script id="world-data" type="application\/json">)[\s\S]*?(<\/script>)/,(_,a,b)=>a+payload+b);}
const readme=()=>`# ${project.title}\n\n${project.brief}\n\nOpen studio.html to edit or walkthrough.html to explore, including offline. Import the .glb into a glTF-capable 3D tool. GLB is Y-up in meters; named objects become meshes. The .vox file is one flattened MagicaVoxel model with a palette, with its Z axis vertical. Keep ${project.id}.tidelands.json: it preserves source objects, rotations, locks, materials, scale, spawn and destinations. Browser undo history is temporary.\n\nOne voxel = ${project.unit} meters. The visitor is 1.7 m tall and 0.52 m wide. Route checks are finite geometry checks, not a substitute for walking the result. No game rules, networking or physical construction certification are included.\n\n${project.notes}\n`;
$('save-project').onclick=()=>download(project.id+'.tidelands.json',JSON.stringify(project,null,2),'application/json');
$('deliver').onclick=()=>{$('export-summary').textContent=project.title+' · '+world.count.toLocaleString()+' voxels · '+project.objects.filter(o=>!o.hidden).length+' visible objects';$('export-dialog').showModal();};$('close-export').onclick=()=>$('export-dialog').close();
$('export-glb').onclick=guard(()=>download(project.id+'.glb',exportGLB(project),'model/gltf-binary'));$('export-vox').onclick=guard(()=>download(project.id+'.vox',exportVOX(project)));$('export-walk').onclick=()=>download(project.id+'-walkthrough.html',portable('walk'),'text/html');
$('export-kit').onclick=guard(async()=>{report('Preparing your editable world kit…');await new Promise(r=>setTimeout(r,30));const files=[[project.id+'.tidelands.json',JSON.stringify(project,null,2)],[project.id+'.glb',exportGLB(project)],[project.id+'.vox',exportVOX(project)],['studio.html',portable()],['walkthrough.html',portable('walk')],['README.md',readme()],['walking-check.json',JSON.stringify(navigationReport(project),null,2)]];download(project.id+'-world-kit.zip',zipFiles(files));report('World kit exported: source, GLB, VOX, editable studio and walkthrough');});
$('snapshot').onclick=()=>{renderer.render(scene,camera);renderer.domElement.toBlob(blob=>{if(blob)download(project.id+'-'+stamp()+'.png',blob);});};
$('check-routes').onclick=guard(()=>{const result=navigationReport(project);report(result.issues.length?result.issues.join(' '):`${result.reachableStandingCells.toLocaleString()} connected standing positions; all ${result.stops.length} destinations reached by the geometry check. Walk the result to verify it.`);download(project.id+'-walking-check.json',JSON.stringify(result,null,2),'application/json');});
function openProject(next,message){const valid=validateProject(next);meshWorld(valid);session.openDraft(valid);project=session.project;selected=project.objects.find(o=>!o.locked)?.id??project.objects[0].id;rebuild();if(walking)setWalking(false);frame();report(message);saveDraft();}
$('open-project').onclick=guard(async()=>{$('native-open').hidden=!connected;$('open-dialog').showModal();if(connected){const response=await fetch('/api/files'),data=await response.json();$('recent-projects').replaceChildren();for(const file of data.files??[]){const button=document.createElement('button');button.className='wide';button.textContent=file.name;button.title=file.folder;button.onclick=guard(()=>openPath(file.path));$('recent-projects').append(button);}if(!data.files?.length)$('recent-projects').textContent='No saved worlds in Downloads, Desktop or Documents yet.';}});
$('choose-project').onclick=()=>$('project-file').click();$('close-open').onclick=()=>$('open-dialog').close();
async function openPath(path){const response=await fetch('/api/open',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({path})}),data=await response.json();if(!response.ok)throw new Error(data.error||'Could not open the project.');openProject(data.project,'Project opened as a draft. Save to keep it in this workspace.');$('open-dialog').close();}
$('open-path').onclick=guard(()=>openPath($('project-path').value));
$('project-file').onchange=guard(async event=>{const f=event.target.files[0];event.target.value='';if(!f)return;if(f.size>12000000)throw new Error('Choose a project smaller than 12 MB.');openProject(JSON.parse(await f.text()),'Project opened as a draft. Save to keep it in this workspace.');$('open-dialog').close();});
$('import-vox').onclick=()=>$('vox-file').click();$('vox-file').onchange=guard(async event=>{const f=event.target.files[0];event.target.value='';if(!f)return;if(f.size>24000000)throw new Error('Choose a VOX file smaller than 24 MB.');const asset=importVOX(await f.arrayBuffer()),origin=[0,Math.floor(project.spawn.position[1]),0],result=addImportedAsset(project,asset,{name:f.name.replace(/\.vox$/i,''),origin});mutate(p=>Object.assign(p,result.project),'Supplied voxel asset imported');setSelected(result.id);});
function sourceNotice(next,message){sourcePending=next;session.observeSource(next);$('source-notice').hidden=false;$('source-notice').querySelector('span').textContent=message;state();saveDraft();}
$('draft-keep').onclick=()=>download(project.id+'-draft-'+stamp()+'.tidelands.json',JSON.stringify(project,null,2),'application/json');
function acceptSource(next,message){const valid=validateProject(next);meshWorld(valid);session.acceptSource(valid);project=session.project;if(!selectedObject())selected=project.objects.find(o=>!o.locked&&!o.hidden)?.id??project.objects[0].id;rebuild();report(message);saveDraft();}
$('source-load').onclick=guard(()=>{if(!sourcePending)return;download(project.id+'-before-restore-'+stamp()+'.tidelands.json',JSON.stringify(project,null,2),'application/json');acceptSource(sourcePending,'Prior draft downloaded; source version restored');sourcePending=null;if(walking)setWalking(false);frame();$('source-notice').hidden=true;state();});
$('save-source').onclick=guard(async()=>{
  if(!connected||sourcePending||saving||!session.dirty)return;
  const request=session.beginSave();saving=true;pollEpoch++;state();
  try{
    const response=await fetch('/api/project',{method:'PUT',headers:{'content-type':'application/json','if-match':request.revision},body:request.body}),result=await response.json();
    if(response.status===409){sourceNotice(validateProject(result.project),'The source changed while you were editing. Download your draft before choosing the source.');return;}
    if(!response.ok)throw new Error(result.error||'Save failed');
    const keptEdits=session.finishSave(request,validateProject(result.project));project=session.project;
    report(keptEdits?'Saved the submitted version; your newer edits are still unsaved.':'Saved to workspace; the previous source is retained in history.');saveDraft();
  }finally{saving=false;state();}
});
async function poll(){if(location.protocol==='file:'||readonly||saving)return;const epoch=++pollEpoch;try{const response=await fetch('/api/project');if(!response.ok)return;const result=await response.json();if(epoch!==pollEpoch||saving||!result.project)return;connected=true;const next=validateProject(result.project);if(next.revision!==session.revision){if(session.dirty)sourceNotice(next,'Your agent changed the source. Keep your draft before switching versions.');else acceptSource(next,'Agent changes loaded from the source project');}state();}catch{}}
document.body.classList.toggle('readonly',readonly);rebuild();frame();resize();setTool('select');requestAnimationFrame(animate);
if(readonly){guard(()=>setWalking(true))();$('save-state').textContent='Offline walkthrough';}else{
  try{const draft=JSON.parse(localStorage.getItem(session.draftKey)||'null');if(draft?.project&&JSON.stringify(draft.project)!==JSON.stringify(project)){const source=project;openProject(draft.project,'Recovered your browser draft');sourceNotice(source,'A previous browser draft was recovered. You can keep it or return to the saved source.');}}catch{}
  poll();setInterval(poll,3000);
}
// The same live state used by the controls is exposed for finite browser acceptance checks.
window.tidelands={get project(){return clone(project);},get world(){return world;},get visitor(){return clone(visitor);},get selected(){return selected;},screenPoint(point){const q=new THREE.Vector3(...point).project(camera),r=renderer.domElement.getBoundingClientRect();return {x:r.x+(q.x+1)/2*r.width,y:r.y+(1-q.y)/2*r.height};},get connected(){return connected;},get dirty(){return session.dirty;},setSelected,exportGLB:()=>exportGLB(project),exportVOX:()=>exportVOX(project),portable,navigationReport:()=>navigationReport(project)};
