import {mkdtemp,cp,mkdir,writeFile,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
import {chromium} from '../toolchain/node_modules/playwright-core/index.mjs';
import {browserPath} from '../toolchain/browser.mjs';
import {createWorldViewer} from '../viewer/viewer.mjs';
import {buildWorld} from '../template/tools/build.mjs';
import {importVOX} from '../template/studio/formats.mjs';
import validator from '../toolchain/node_modules/gltf-validator/index.js';
const root=process.env.VOXEL_QA_ROOT||await mkdtemp(join(tmpdir(),'tidelands-browser-')),workspace=join(root,'workspace');await mkdir(root,{recursive:true});await cp(fileURLToPath(new URL('../template/',import.meta.url)),workspace,{recursive:true});
process.env.VOXEL_DSH_DIR=fileURLToPath(new URL('../',import.meta.url));await buildWorld(workspace);const server=await createWorldViewer(workspace);await new Promise(r=>server.listen(0,'127.0.0.1',r));
const url='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({executablePath:await browserPath(),headless:true,args:['--enable-unsafe-swiftshader']});const context=await browser.newContext({viewport:{width:1440,height:960},acceptDownloads:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
const shot=async name=>{await page.waitForTimeout(500);await page.screenshot({path:join(root,name+'.png')});};
async function downloadClick(selector,name){const promise=page.waitForEvent('download');await page.locator(selector).click();const d=await promise;const path=join(root,name||d.suggestedFilename());await d.saveAs(path);return path;}
try{
  await page.goto(url);await page.waitForFunction(()=>window.tidelands?.connected);await shot('01-studio');assert.deepEqual(errors,[]);
  await page.locator('#edit-project').click();await page.locator('#size-x').fill('4');await page.locator('#apply-project').click();await page.locator('#project-dialog [data-error]').waitFor({state:'visible'});assert.equal(await page.evaluate(()=>window.tidelands.project.size[0]),80);await page.getByRole('button',{name:'Cancel',exact:true}).click();
  await page.locator('[data-object="crates"]').click();await page.locator('#focus-object').click();await page.waitForTimeout(500);await page.locator('[data-tool="paint"]').click();await page.locator('[data-material="8"]').click();const top=await page.evaluate(()=>window.tidelands.screenPoint([44.5,10,30.5]));await page.mouse.click(top.x,top.y);await page.waitForFunction(()=>window.tidelands.project.objects.find(o=>o.id==='crates').edits.length>0);await shot('02-sculpted');await page.locator('#undo').click();assert.equal(await page.evaluate(()=>window.tidelands.project.objects.find(o=>o.id==='crates').edits.length),0);await page.locator('[data-tool="select"]').click();await page.locator('#frame-world').click();
  await page.locator('[data-object="bakery"]').click();await page.locator('#object-name').fill('Approved bakery');await page.locator('#object-name').press('Tab');await page.waitForFunction(()=>window.tidelands.project.objects.find(o=>o.id==='bakery').name==='Approved bakery');
  await page.locator('[data-position="0"]').fill('7');await page.locator('[data-position="0"]').press('Tab');await page.locator('#rotate-object').click();assert.equal(await page.evaluate(()=>window.tidelands.project.objects.find(o=>o.id==='bakery').origin[0]),7);await shot('02-edited');
  await page.locator('#undo').click();assert.equal(await page.evaluate(()=>window.tidelands.project.objects.find(o=>o.id==='bakery').rotation),2);await page.locator('#redo').click();
  await page.locator('#save-source').click();await page.waitForFunction(()=>!window.tidelands.dirty);const saved=JSON.parse(await readFile(join(workspace,'world/project.json'),'utf8'));assert.equal(saved.objects.find(o=>o.id==='bakery').name,'Approved bakery');
  await page.locator('#object-name').fill('Browser draft bakery');await page.locator('#object-name').press('Tab');const external=structuredClone(saved);external.objects.find(o=>o.id==='boat').name='Agent revised skiff';await writeFile(join(workspace,'world/project.json'),JSON.stringify(external));await buildWorld(workspace);await page.locator('#source-notice').waitFor({state:'visible'});const draft=await downloadClick('#draft-keep','conflict-draft.tidelands.json');assert.equal(JSON.parse(await readFile(draft,'utf8')).objects.find(o=>o.id==='bakery').name,'Browser draft bakery');
  await downloadClick('#source-load','before-source-restore.tidelands.json');await page.waitForFunction(()=>window.tidelands.project.objects.find(o=>o.id==='boat').name==='Agent revised skiff');assert.equal(await page.evaluate(()=>window.tidelands.project.objects.find(o=>o.id==='bakery').name),'Approved bakery');
  await page.locator('[data-object="boat"]').click();const glbPath=await downloadClick('#asset-glb','skiff.glb'),voxPath=await downloadClick('#asset-vox','skiff.vox');const validation=await validator.validateBytes(new Uint8Array(await readFile(glbPath)),{});assert.equal(validation.issues.numErrors,0);const supplied=importVOX(await readFile(voxPath));assert.deepEqual(supplied.size,[6,4,15]);
  await page.locator('#vox-file').setInputFiles(voxPath);await page.waitForFunction(()=>window.tidelands.project.objects.some(o=>o.name==='skiff'));await page.locator('#undo').click();
  await page.locator('#deliver').click();const kit=await downloadClick('#export-kit','world-kit.zip'),walk=await downloadClick('#export-walk','walkthrough.html');await page.locator('#close-export').click();
  await page.locator('#walk-mode').click();await page.locator('#viewport').click({position:{x:700,y:700}});const before=await page.evaluate(()=>window.tidelands.visitor.position);await page.keyboard.down('w');await page.waitForTimeout(1100);await page.keyboard.up('w');const after=await page.evaluate(()=>window.tidelands.visitor.position);assert.ok(Math.hypot(before[0]-after[0],before[2]-after[2])>1);await shot('03-walk');
  const beforeRight=await page.evaluate(()=>window.tidelands.visitor.position[0]);await page.keyboard.down('d');await page.waitForTimeout(300);await page.keyboard.up('d');assert.ok(await page.evaluate(()=>window.tidelands.visitor.position[0])>beforeRight,'D strafes to the camera right');
  await page.locator('[data-stop="pier"]').click();await shot('04-pier');await page.locator('#edit-mode').click();
  const offline=await context.newPage();await context.setOffline(true);await offline.goto(pathToFileURL(walk).href);await offline.waitForFunction(()=>window.tidelands?.visitor);assert.equal(await offline.evaluate(()=>window.tidelands.project.objects.find(o=>o.id==='boat').name),'Agent revised skiff');await offline.screenshot({path:join(root,'05-offline-walk.png')});await context.setOffline(false);
  const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),phone=await mobile.newPage();await phone.goto(url);await phone.waitForFunction(()=>window.tidelands);await phone.locator('#walk-mode').click();await phone.locator('[data-move="forward"]').waitFor({state:'visible'});await phone.screenshot({path:join(root,'06-mobile.png')});await mobile.close();
  assert.deepEqual(errors,[]);const report={root,workspace,url,kit,glbErrors:validation.issues.numErrors,walkDistanceCells:Math.hypot(before[0]-after[0],before[2]-after[2]),browserErrors:errors,checks:['direct voxel painting and undo','edit object and position','rotate/undo/redo','save source','agent/browser conflict with both drafts retained','independent selected GLB validation','VOX import','complete kit download','actual keyboard walking','tour stop','offline walkthrough reopen','mobile walking controls']};await writeFile(join(root,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));}
