// Generated by desktop/tool/store_catalog_history.mjs.
// Publication source: c0034c2d7dc072384d57e0562f994e51e483c2ff
// A snapshot for this app release; unknown tools are never assigned fake dates.
const storeCatalogHistory = <String, ({String addedAt, String updatedAt})>{
  'autonomous/ableton-ai': (
    addedAt: '2026-09-18T02:52:29.000Z',
    updatedAt: '2026-09-18T04:18:33.000Z',
  ),
  'autonomous/autonomous-circuit': (
    addedAt: '2026-09-17T05:18:32.000Z',
    updatedAt: '2026-09-18T03:26:29.000Z',
  ),
  'autonomous/autonomous-grid': (
    addedAt: '2026-09-18T07:20:25.000Z',
    updatedAt: '2026-09-20T07:04:49.000Z',
  ),
  'autonomous/autonomous-workshop': (
    addedAt: '2026-09-17T05:18:32.000Z',
    updatedAt: '2026-09-18T03:26:29.000Z',
  ),
  'autonomous/autoresearch-mlx': (
    addedAt: '2026-09-18T02:52:29.000Z',
    updatedAt: '2026-09-18T04:18:33.000Z',
  ),
  'autonomous/blender': (
    addedAt: '2026-09-17T05:18:32.000Z',
    updatedAt: '2026-09-18T03:26:29.000Z',
  ),
  'autonomous/bonsai-mcp': (
    addedAt: '2026-09-18T02:52:29.000Z',
    updatedAt: '2026-09-18T04:18:33.000Z',
  ),
  'autonomous/circuitjs': (
    addedAt: '2026-09-17T05:18:32.000Z',
    updatedAt: '2026-09-18T03:26:29.000Z',
  ),
  'autonomous/comfy-mcp': (
    addedAt: '2026-09-18T02:52:29.000Z',
    updatedAt: '2026-09-18T04:18:33.000Z',
  ),
  'autonomous/creative-direction': (
    addedAt: '2026-09-19T16:47:24.000Z',
    updatedAt: '2026-09-20T08:21:01.000Z',
  ),
  'autonomous/data-studio': (
    addedAt: '2026-09-19T19:26:36.000Z',
    updatedAt: '2026-09-20T08:21:01.000Z',
  ),
  'autonomous/dimos': (
    addedAt: '2026-09-18T02:52:29.000Z',
    updatedAt: '2026-09-18T04:18:33.000Z',
  ),
  'autonomous/drone-pilot': (
    addedAt: '2026-09-19T16:47:24.000Z',
    updatedAt: '2026-09-20T10:41:34.000Z',
  ),
  'autonomous/excalidraw': (
    addedAt: '2026-09-17T05:18:32.000Z',
    updatedAt: '2026-09-18T03:26:29.000Z',
  ),
  'autonomous/foam-agent': (
    addedAt: '2026-09-18T02:52:29.000Z',
    updatedAt: '2026-09-18T04:18:33.000Z',
  ),
  'autonomous/freecad': (
    addedAt: '2026-09-19T19:26:36.000Z',
    updatedAt: '2026-09-20T02:53:00.000Z',
  ),
  'autonomous/game-master': (
    addedAt: '2026-09-19T16:47:24.000Z',
    updatedAt: '2026-09-20T11:45:05.000Z',
  ),
  'autonomous/generative-art': (
    addedAt: '2026-09-19T16:47:24.000Z',
    updatedAt: '2026-09-20T03:19:57.000Z',
  ),
  'autonomous/godogen': (
    addedAt: '2026-09-17T06:19:35.000Z',
    updatedAt: '2026-09-18T03:26:29.000Z',
  ),
  'autonomous/home-assistant': (
    addedAt: '2026-09-19T19:26:36.000Z',
    updatedAt: '2026-09-20T16:15:08.000Z',
  ),
  'autonomous/jev-browser': (
    addedAt: '2026-09-19T17:24:55.000Z',
    updatedAt: '2026-09-20T14:36:44.000Z',
  ),
  'autonomous/jev-sheets': (
    addedAt: '2026-09-19T17:24:55.000Z',
    updatedAt: '2026-09-20T14:36:44.000Z',
  ),
  'autonomous/juce-agent-toolkit': (
    addedAt: '2026-09-18T02:52:29.000Z',
    updatedAt: '2026-09-18T04:18:33.000Z',
  ),
  'autonomous/kicad': (
    addedAt: '2026-09-18T08:31:05.000Z',
    updatedAt: '2026-09-18T08:31:05.000Z',
  ),
  'autonomous/lab-bench': (
    addedAt: '2026-09-19T16:47:24.000Z',
    updatedAt: '2026-09-20T13:10:38.000Z',
  ),
  'autonomous/machine-monitor': (
    addedAt: '2026-09-20T23:16:16.000Z',
    updatedAt: '2026-09-20T23:16:16.000Z',
  ),
  'autonomous/manim': (
    addedAt: '2026-09-17T05:18:32.000Z',
    updatedAt: '2026-09-18T03:26:29.000Z',
  ),
  'autonomous/marimo': (
    addedAt: '2026-09-17T05:18:32.000Z',
    updatedAt: '2026-09-18T03:26:29.000Z',
  ),
  'autonomous/marp': (
    addedAt: '2026-09-17T05:18:32.000Z',
    updatedAt: '2026-09-18T03:26:29.000Z',
  ),
  'autonomous/mlx-lm': (
    addedAt: '2026-09-20T07:04:49.000Z',
    updatedAt: '2026-09-20T07:04:49.000Z',
  ),
  'autonomous/mujoco': (
    addedAt: '2026-09-17T05:18:32.000Z',
    updatedAt: '2026-09-18T03:26:29.000Z',
  ),
  'autonomous/music-studio': (
    addedAt: '2026-09-19T16:47:24.000Z',
    updatedAt: '2026-09-20T03:19:57.000Z',
  ),
  'autonomous/ollama': (
    addedAt: '2026-09-20T07:04:49.000Z',
    updatedAt: '2026-09-20T07:04:49.000Z',
  ),
  'autonomous/openmontage': (
    addedAt: '2026-09-17T08:49:09.000Z',
    updatedAt: '2026-09-18T03:26:29.000Z',
  ),
  'autonomous/openscad': (
    addedAt: '2026-09-19T19:26:36.000Z',
    updatedAt: '2026-09-20T05:16:06.000Z',
  ),
  'autonomous/orca-slicer': (
    addedAt: '2026-09-19T19:26:36.000Z',
    updatedAt: '2026-09-20T06:34:49.000Z',
  ),
  'autonomous/phaser': (
    addedAt: '2026-09-17T05:18:32.000Z',
    updatedAt: '2026-09-18T03:26:29.000Z',
  ),
  'autonomous/rdkit': (
    addedAt: '2026-09-17T05:18:32.000Z',
    updatedAt: '2026-09-18T03:26:29.000Z',
  ),
  'autonomous/remotion': (
    addedAt: '2026-09-17T05:18:32.000Z',
    updatedAt: '2026-09-18T03:26:29.000Z',
  ),
  'autonomous/roundtable': (
    addedAt: '2026-09-20T10:44:03.000Z',
    updatedAt: '2026-09-20T11:02:44.000Z',
  ),
  'autonomous/score': (
    addedAt: '2026-09-19T19:26:36.000Z',
    updatedAt: '2026-09-20T08:23:36.000Z',
  ),
  'autonomous/simskill': (
    addedAt: '2026-09-18T02:52:29.000Z',
    updatedAt: '2026-09-18T04:18:33.000Z',
  ),
  'autonomous/strudel': (
    addedAt: '2026-09-17T05:18:32.000Z',
    updatedAt: '2026-09-18T03:26:29.000Z',
  ),
  'autonomous/text-to-cad': (
    addedAt: '2026-09-17T05:18:32.000Z',
    updatedAt: '2026-09-18T03:26:29.000Z',
  ),
  'autonomous/typst': (
    addedAt: '2026-09-17T05:18:32.000Z',
    updatedAt: '2026-09-18T03:26:29.000Z',
  ),
  'autonomous/vllm': (
    addedAt: '2026-09-20T07:04:49.000Z',
    updatedAt: '2026-09-20T07:04:49.000Z',
  ),
  'autonomous/voxel-worlds': (
    addedAt: '2026-09-19T16:47:24.000Z',
    updatedAt: '2026-09-20T10:41:34.000Z',
  ),
  'autonomous/yosys': (
    addedAt: '2026-09-17T05:18:32.000Z',
    updatedAt: '2026-09-18T03:26:29.000Z',
  ),
};
