import {el,toolbar,badge,label} from '/graphics.mjs';
export function mount(stage,api){
  let p=api.getParameters(),result,selected=-1,last='',dialog;
  const tag=badge(stage,'PROCEDURAL STUDIES'),info=label(stage,'A family of forms. Pick the one that speaks to you.');
  const gallery=el('div','','gallery');stage.append(gallery);
  function close(){dialog?.close();dialog?.remove();dialog=null;gallery.children[Math.max(0,selected)]?.focus();}
  function inspect(index){const img=result?.data?.images?.[index];if(!img)return;close();selected=index;dialog=el('dialog','','domain-dialog');dialog.setAttribute('aria-label','Inspect study');const b=el('button','Close');b.addEventListener('click',()=>{close();gallery.children[index]?.focus();});const picture=el('img');picture.src=api.artifactURL(result.artifacts.find(a=>a.path.endsWith('/'+img.name)).path);picture.alt=img.seed===null?'ComfyUI workflow output':`Procedural study ${img.seed}`;dialog.append(b,el('h2',img.seed===null?'ComfyUI output':`Study ${String(img.seed).padStart(4,'0')}`),picture,el('p',img.seed===null?'Produced by your saved ComfyUI workflow.':`Reproduce this study with seed ${img.seed} and the saved recipe.`));stage.append(dialog);dialog.addEventListener('cancel',e=>{e.preventDefault();close();});dialog.showModal();b.focus();api.announce('Study opened.');}
  stage.addEventListener('keydown',e=>{if(e.key==='Escape')close();});
  toolbar(stage,[['Another family',()=>api.setParameter('seed',p.seed%980+7)],['Inspect favourite',()=>inspect(selected<0?0:selected)]]);
  return {update(params,r){p=params;result=r;if(!r?.data?.images){gallery.replaceChildren(el('div','Grow a family of variations to explore.','domain-empty'));return;}if(r.id===last)return;last=r.id;close();gallery.replaceChildren();tag.textContent=r.engine.startsWith('Native')?'COMFYUI OUTPUTS':'PROCEDURAL STUDIES';r.data.images.forEach((img,i)=>{const file=r.artifacts.find(a=>a.path.endsWith('/'+img.name));if(!file)return;const button=el('button');button.type='button';button.setAttribute('aria-label',img.seed===null?`Inspect image ${i+1}`:`Inspect study ${img.seed}`);const image=el('img');image.src=api.artifactURL(file.path);image.alt=img.seed===null?'ComfyUI output':`A ${r.parameters.palette} procedural flower, seed ${img.seed}`;const caption=el('figcaption',img.seed===null?`Output ${i+1}`:`No. ${String(img.seed).padStart(4,'0')}  ↗`);button.append(image,caption);button.addEventListener('click',()=>inspect(i));gallery.append(button);});}};
}
