import {readFileSync} from 'node:fs';
const esc=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const fmt=value=>Number(value.toFixed(2)).toLocaleString('en-US');
const size=mesh=>mesh.bounds.size.map(fmt).join(' × ');
const notes=items=>'<ul>'+items.map(note=>'<li>'+esc(note)+'</li>').join('')+'</ul>';
export function handoff(report){
  const design=report.design,total=report.checks.length;
  const differing=Object.keys(design.parameters).filter(name=>new Set(report.variants.map(variant=>variant.parameters[name])).size>1);
  const checksFor=variant=>report.checks.filter(c=>c.variant===variant.id);
  const compare=report.variants.map(variant=>'<tr><th scope="row">'+esc(variant.label)+'</th>'+differing.map(name=>'<td>'+fmt(variant.parameters[name])+' <small>'+esc(design.parameters[name].unit)+'</small></td>').join('')+'<td>'+variant.parts.map(part=>esc(part.label)+': '+size(part.printMesh)+' mm').join('<br>')+'</td><td class="pass">All passed</td></tr>').join('');
  const tabs=report.variants.map((variant,i)=>'<button type="button" data-variant="'+variant.id+'" aria-pressed="'+(variant.id===design.preview.variant)+'">'+esc(variant.label)+'</button>').join('');
  const panels=report.variants.map((variant,i)=>'<section class="variant" id="variant-'+variant.id+'" data-panel="'+variant.id+'"'+(variant.id===design.preview.variant?'':' hidden')+'><div class="section-heading"><div><p class="eyebrow">SAVED CONFIGURATION</p><h2>'+esc(variant.label)+'</h2></div><span class="pill">'+variant.parts.length+' part'+(variant.parts.length>1?'s':'')+' · '+checksFor(variant).length+' passed checks</span></div>'+
    (variant.notes.length?'<p class="muted">'+variant.notes.map(esc).join(' ')+'</p>':'')+
    '<div class="parameters">'+Object.entries(variant.parameters).map(([name,value])=>'<div><span>'+esc(design.parameters[name].label||name.replaceAll('_',' '))+'</span><strong>'+fmt(value)+' <small>'+esc(design.parameters[name].unit)+'</small></strong></div>').join('')+'</div>'+
    variant.parts.map(part=>'<article class="part"><div class="part-heading"><div><p class="eyebrow">PART · '+esc(part.id)+'</p><h3>'+esc(part.label)+'</h3></div><a class="button" download href="'+part.path.replace('handoff/','')+'">Download STL <span aria-hidden="true">↗</span></a></div><div class="part-facts"><span><b>'+size(part.printMesh)+'</b> mm · print size</span><span><b>'+fmt(part.mesh.volumeMM3/1000)+'</b> cm³ · model volume</span><span><b>'+part.quantity+'</b> needed · print separately</span></div><div class="views">'+part.views.map(view=>'<figure><div class="view"><img src="'+view.path.replace('handoff/','')+'" alt="'+esc(part.label+' '+view.name+' '+(view.at===null?'silhouette':'section at '+fmt(view.at)+' mm'))+'"></div><figcaption><span>'+view.name+' · '+view.axes+'</span><span>'+(view.at===null?'Silhouette':'Section @ '+fmt(view.at)+' mm')+'</span></figcaption></figure>').join('')+'</div><p class="caption">Reference views use design coordinates. The STL is rotated ['+part.printRotation.join(', ')+']° and moved onto the bed. Inspect the actual mesh in the CAD Viewer before slicing.</p>'+
    (part.notes.length?notes(part.notes):'')+'<details><summary>Part dimensions &amp; file identity</summary><p>Design bounds: '+size(part.mesh)+' mm. Minimum corner: ['+part.mesh.bounds.min.map(fmt).join(', ')+'] mm.</p><p>'+part.mesh.triangles.toLocaleString('en-US')+' triangles · '+part.mesh.shells.length+' connected surface shell(s) · closed, positively oriented mesh.</p><p class="hash">STL SHA-256: '+part.sha256+'</p><a download href="source-previews/'+variant.id+'-'+part.id+'.scad">Editable configuration wrapper</a> <span class="muted">(use inside the complete project)</span></details></article>').join('')+
    '<details class="checks"><summary>'+checksFor(variant).length+' measured checks — inspect the evidence</summary><div>'+checksFor(variant).map(check=>'<div class="check"><span class="pass" aria-label="Passed">✓</span><div><b>'+esc(check.label)+'</b><p>'+esc(check.detail)+'</p></div></div>').join('')+'</div></details></section>').join('');
  return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>'+esc(design.title)+' · OpenSCAD</title><style>'+readFileSync(new URL('handoff.css',import.meta.url),'utf8')+'</style><script defer src="app.js"></script></head><body><header><div class="brand"><span class="mark" aria-hidden="true">⬡</span> OPENSCAD / WORKSHOP</div><div class="snapshot">Saved build · '+esc(report.engine.replace('OpenSCAD version ',''))+'<br>Revision '+report.sourceRevision.slice(0,12)+'</div></header><main><section class="hero"><div><p class="eyebrow">YOUR MEASUREMENTS. A FAMILY OF PARTS.</p><h1>'+esc(design.title)+'</h1><p class="brief">'+esc(design.brief)+'</p></div><div class="primary"><a class="button" href="project.zip" download>Download complete project <span aria-hidden="true">↓</span></a><p>Editable source · every STL · rebuild tools</p></div></section><div class="metrics"><div><b>'+report.variants.length+'</b><span>saved size / fit variants</span></div><div><b>'+design.parts.length+'</b><span>unique parts per variant</span></div><div><b class="pass">'+total+' / '+total+'</b><span>measured checks passed</span></div><div><b>'+esc(design.process.material)+'</b><span>'+fmt(design.process.nozzleMM)+' mm nozzle · declared process</span></div></div><div class="section-heading"><h2>Compare the family</h2><span class="pill">Individual fit · '+design.process.bedMM.map(fmt).join(' × ')+' mm build envelope</span></div><details class="family-comparison"><summary>Compare dimensions across all configurations</summary><div class="table-scroll"><table><thead><tr><th scope="col">Configuration</th>'+differing.map(name=>'<th scope="col">'+esc(design.parameters[name].label||name.replaceAll('_',' '))+'</th>').join('')+'<th scope="col">Oriented part dimensions</th><th scope="col">Requirements</th></tr></thead><tbody>'+compare+'</tbody></table></div></details><div class="tabs" role="group" aria-label="Choose configuration">'+tabs+'</div>'+panels+'<section class="notes-grid"><div><h3>Measured brief &amp; assumptions</h3>'+notes(design.assumptions)+'</div><div><h3>Make &amp; use</h3>'+notes([...design.process.notes,...design.assembly])+'</div></section><aside class="notice"><b>Checked geometry. Physical validation still matters.</b>'+report.limitations.map(item=>'<p>'+esc(item)+'</p>').join('')+'<p>This is the last successful build, not a live view of current source edits. Rebuild before using a changed design.</p></aside></main><footer><div class="footer-row"><div><a href="checks.json" download>Download measured report</a><a href="project.zip" download>Portable project</a></div><span>Native OpenSCAD · no cloud dependency</span></div><p class="hash">Source SHA-256: '+report.sourceRevision+'</p></footer></body></html>';
}
